### ISSUE TITLE
Improve user flow after placing the contro

### ISSUE THREAD

**Issue by mitfik** [THCLab/oca-editor#14]
It is not obvious for the user that double click on the control gives options. 

We need to make sure that user would be guided over the process and that it will be smooth for him. 

To improve the process we could:
- change double click on one click to select control and display options
- after start dragging the input some bin should be showed so user can understand how to remove it (or just display delete on side of apply and cancel)
- after dropping control options could be opened automatically

**Comment by blelump** [comment]
In this case I'd vote for an edit button. It makes the UI straightforward and makes it consistent across all platforms (mobile etc). The current UI is almost good and need to be polished a bit :smile: .
